spring:
  application:
    name: study-server

  config:
    activate:
      on-profile: "prod"

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ENC(KfoCUh6ZJPswSFpcuxxaMsTh/fp1hgr9bAntA6bQGBzsltWz4Bm7wZ0FdwuUWNBhSp562Q9CAgGGt4Lr6PNzb4cI70s/IMq/ZnNY4MsOAdmIXIkTNo4jYgz48dxjxZfxGyrXhoGy/UEpnOULSwgLrPcAbOp/3gzmYnZPbr0uxCQ=)
    username: ENC(Xp6n1CvQn5kuYr7H5CVFTA==)
    password: ENC(dv0ChLPj92uKpx41cw/+IGvOZeVgCbY+)
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: ENC(2vs2h50LHu9p/WFRDyH9M8Kvtn6Trbjp)
#    port: 6377