spring:
  application:
    name: study-server

  config:
    activate:
      on-profile: "prod"

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ENC(8H0WSZXzgetPmawJXohtjmsLhcBksRK/8i6H9pVTXsDX7LG+NHk+n30EKshNVSfYNJ2Sb6lnfpnJIQ/0W+LrRn/gV3FDtWKhgr14Yam5LO4JOYB3SWeeXc8m1FUCevAg4vH8cCvSw0HND0wkvtrBAOfXtiI2RJzysgasGBdxl5c=)
    username: ENC(cK/WxKDOmFR3LMOpvh21uQ==)
    password: ENC(VJVBKjn7uconqIipj4nC7P9Dk7v38mu+)
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: ENC(2vs2h50LHu9p/WFRDyH9M8Kvtn6Trbjp)
#    port: 6377