spring:
  application:
    name: study-server

  profiles:
    include:
      secret

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ENC(i9CJ9asDFyA896CwhmNdIq5QhbToFN9jC3nlHz49oMbapBBOdVqHVo768MWZNKY+86bKUo+AbC4zuHWy4NsKwuUyvpFHzREk5sIZ/G8M0bZTNyV82uusjA==)
    username: ENC(vVTzs/wnFCkvCjrq7S5yWw==)
    password: ENC(HcD6QiG9CfvqrBHRUqQNEw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: ENC(2vs2h50LHu9p/WFRDyH9M8Kvtn6Trbjp)
#    port: 6377